### PR TITLE
Addressing Munki Installs Array

### PR DESCRIPTION
**Pull request by foigus**
This should generate the Installs Array.

### CODE REVIEW

**Comment by BaddMann** [comment]
Is there a bigger benefit to this method over the method that was working before this?
**MunkiInstallsItemsCreator**
Just appeared to use munkiimport to create the install after the fact. It looked clean and did what i perceived to be correct.
Am i missing Something?

**Comment by foigus** [comment]
I ran the recipe (`autopkg run OBS.munki`) as it stood in your repo and got the following pkginfo.  Are you getting an installs array?

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>_metadata</key>
	<dict>
		<key>created_by</key>
		<string>foigus</string>
		<key>creation_date</key>
		<date>2017-03-15T20:57:07Z</date>
		<key>munki_version</key>
		<string>2.8.2.2855</string>
		<key>os_version</key>
		<string>10.12.3</string>
	</dict>
	<key>autoremove</key>
	<false/>
	<key>catalogs</key>
	<array>
		<string>testing</string>
	</array>
	<key>description</key>
	<string>Free and open source software for video recording and live streaming.</string>
	<key>developer</key>
	<string>J. Bradley &amp; Associates, LLC.</string>
	<key>display_name</key>
	<string>OBS Studio</string>
	<key>installed_size</key>
	<integer>211791</integer>
	<key>installer_item_hash</key>
	<string>a0f353fa60ef78862814c1a11cd8e02382e0ec6d761ca1dddb4427ab37408957</string>
	<key>installer_item_location</key>
	<string>apps/OBS/obs-mac-18.0.1-installer-18.0.1.pkg</string>
	<key>installer_item_size</key>
	<integer>82254</integer>
	<key>installs</key>
	<array/>
	<key>minimum_os_version</key>
	<string>10.5.0</string>
	<key>name</key>
	<string>OBS</string>
	<key>receipts</key>
	<array>
		<dict>
			<key>installed_size</key>
			<integer>210905</integer>
			<key>packageid</key>
			<string>org.obsproject.pkg.obs-studio</string>
			<key>version</key>
			<string>1.0</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>886</integer>
			<key>packageid</key>
			<string>zakk.lol.SyphonInject</string>
			<key>version</key>
			<string>1.3</string>
		</dict>
	</array>
	<key>unattended_install</key>
	<true/>
	<key>uninstall_method</key>
	<string>removepackages</string>
	<key>uninstallable</key>
	<true/>
	<key>version</key>
	<string>18.0.1</string>
</dict>
</plist>
```

**Comment by BaddMann** [comment]
I was.....

**Comment by foigus** [comment]
AutoPkg needs something to ingest in order to create a usable installs array.  That something needs to be already existing during the recipe run.  Unless a Mac _happens_ to already have `/Applications/OBS.app` as described [here](https://github.com/BaddMann/autopkg-Recipes/blob/cacdd769094c278aadbaa584ce7b0eba7bc96e5f/OBS-Studio/OBS.munki.recipe#L43-L53), the recipe will fail.

Idempotent handling of building the Munki `installs` array inside the recipe requires:

- [Unpacking the flat package](https://github.com/foigus/autopkg-Recipes/blob/18efb49ff22cf3d6597e082099c5df4657e19097/OBS-Studio/OBS.munki.recipe#L43-L55)
- [Creating a faux filesystem root](https://github.com/foigus/autopkg-Recipes/blob/18efb49ff22cf3d6597e082099c5df4657e19097/OBS-Studio/OBS.munki.recipe#L56-L66)
- [Unpacking the expanded package's payload into the faux root](https://github.com/foigus/autopkg-Recipes/blob/18efb49ff22cf3d6597e082099c5df4657e19097/OBS-Studio/OBS.munki.recipe#L67-L79)
- [Creating an `installs` item](https://github.com/foigus/autopkg-Recipes/blob/18efb49ff22cf3d6597e082099c5df4657e19097/OBS-Studio/OBS.munki.recipe#L80-L92)
- [Merging that information with the existing Munki pkginfo](https://github.com/foigus/autopkg-Recipes/blob/18efb49ff22cf3d6597e082099c5df4657e19097/OBS-Studio/OBS.munki.recipe#L93-L96)

I think your existing recipe may have been working because the Mac in question already had `/Applications/OBS.app` installed.

**Comment by BaddMann** [comment]
I realized that. Now I need to commit your change.

Thank you tons!

**Comment by BaddMann** [comment]
Code well done!
Commiting

**Comment by foigus** [comment]
I think you need to merge this :-)

**Comment by BaddMann** [comment]
Can you tell I'm not that comfortable with GitHub just yet?

**Comment by foigus** [comment]
Heh, my `git` comfortability is summed up by this quote from _Airplane!_:

_"I know but this guy has no flying experience at all. He's a menace to himself and everything else in the air...yes, birds too."_

**Pull request merged**
